services:
  # Frontend React App
  - type: web
    name: concurso-clicker-app
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Permissions-Policy
        value: serial=*
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: require-corp
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Quiz Backend API
  - type: web
    name: quiz-backend
    env: node
    plan: free
    rootDir: ./quiz-backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /health

  # Virtual Clicker Simulator
  - type: web
    name: virtual-clicker
    env: node
    plan: free
    rootDir: ./virtual-clicker
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: QUIZ_BACKEND_URL
        sync: false # Se configurará manualmente con la URL del backend
    healthCheckPath: /api/status
