services:
  - type: web
    name: virtual-clicker
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: QUIZ_BACKEND_URL
        value: https://quiz-backend-YOUR_BACKEND_URL.onrender.com
    healthCheckPath: /api/status
